# Generated by Django 5.1.2 on 2024-11-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='inversor',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estacion'),
        ),
    ]
